---
- hosts: localhost
  gather_facts: no
  vars:
    docker_image: bind_centos
    docker_filepath: ../docker_images/hv_bind_centos/
    packages:
       - docker
    dns_containers:
      provider:
        dns_name: hv_dns
        publish_port: 79

  tasks:
    - debug:
         msg: "{{dns_containers}}"
  
  # Install required packages
    - name: Install required packages for docker
      apt: 
        name: "{{packages}}"
      become: yes

   # Create docker image if not exists
    - name: Create docker image if not exists
      docker_image:
        path: "{{docker_filepath}}"
        name: "{{docker_image}}"
        state: present

    # Create shared volum in HV
    - name: Create shared volume in Hypervisor
      file: 
          path: "/srv/docker/{{dns_containers[item].dns_name}}"
          state: directory
          mode: 0777
      with_items: "{{ dns_containers | list }}"
      become: true
      
    # Create container for dns
    - name: Create and start container for dns if already not present
      docker_container:
        name: "{{dns_containers[item].dns_name}}"
        image: "{{docker_image}}"
        state: started
        privileged: yes
        interactive: yes
        tty: yes
        detach: yes
        volumes:
          - "/srv/docker/{{dns_containers[item].dns_name}}:/named"
        published_ports:
          - "{{dns_containers[item].publish_port}}:{{dns_containers[item].publish_port}}/udp"
      with_items: "{{ dns_containers | list }}"
    
    # Start named server  
    - name: Start the named
      command: "docker exec -itd {{dns_containers[item].dns_name}} /usr/sbin/named -4 -u named -c /named/etc/named.conf"
      become: yes 
      with_items: "{{ dns_containers | list }}"
