---
- hosts: localhost
  gather_facts: no
  vars:
    docker_image: bind_centos2
    docker_filepath: ./docker_images/bind_centos/
    packages:
       - docker
  vars_files:
    - dns_vars.yml

  tasks:
    - debug:
         msg: "{{dns_containers}}"
  
  # Install required packages
    - name: Install required packages for docker
      apt: 
        name: "{{packages}}"
      become: yes

   # Create docker image if not exists
    - name: Create docker image if not exists
      docker_image:
        path: "{{docker_filepath}}"
        name: "{{docker_image}}"
        state: present

    # Create shared volum in HV
    - name: Create shared volume in Hypervisor
      file: 
          path: "/srv/docker/{{dns_containers[item].dns_name}}"
          state: directory
          mode: 0777
      with_items: "{{ dns_containers | list }}"
      become: true
      
    # Create container for dns
    - name: Create and start container for dns if already not present
      docker_container:
        name: "{{dns_containers[item].dns_name}}"
        image: "{{docker_image}}"
        state: started
        privileged: yes
        interactive: yes
        tty: yes
        detach: yes
        volumes:
          - "/srv/docker/{{dns_containers[item].dns_name}}:/named"
        published_ports:
          - "{{dns_containers[item].publish_port}}:{{dns_containers[item].publish_port}}/udp"
      with_items: "{{ dns_containers | list }}"

    
    # Connect Container with bridge
    - name: Connect Container with bridge
      include_tasks: connect_container_bridge.yaml
      vars:
        container_name: "{{dns_containers[item].dns_name}}"
        bridge_name: "{{dns_containers[item].subnet_name}}"
      with_items: "{{ dns_containers | list }}"

    # Change Resolve.conf file
    - name: Get the ip address assigned to DNS container
      command: "docker inspect -f {%raw%}'{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'{%endraw%} {{container_name}}"
      become: yes
      register: container_ip

    # Configure initial setup in 
    - name: Connect Container with bridge
      include_tasks: configure_dns.yaml
      vars:
        container_name: "{{dns_containers[item].dns_name}}"
        zone_name: "{{dns_containers[item].zone_name}}"
        dns_server_ip: "{{container_ip.stdout}}"
      with_items: "{{ dns_containers | list }}"
    
