---
  # vars passed from parent playbook will be:
  #   container_name: t4_api_dns
  #   zone_name: "api.t4.com"
  #   parent_dns_name: t4_dns

  # Change Resolve.conf file
  - name: Get the ip address assigned to DNS container
    command: "docker inspect -f {%raw%}'{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'{%endraw%} {{container_name}}"
    become: yes
    register: container_ip

  - name: set fact
    set_fact:
       dns_server_ip: "{{container_ip.stdout}}"

  # Configure named.conf
  - name: Configure named.conf
    template:
      src: ./templates/dns_conf/named.conf.j2
      dest: /srv/docker/{{container_name}}/etc/named.conf
      mode: 0777
    become: true

  # Configure forward.conf
  - name: Configure forward.conf
    template:
      src: ./templates/dns_conf/forward.com.j2
      dest: /srv/docker/{{container_name}}/var/forward{{zone_name}}
      mode: 0777
    become: true 
  
  # Restart named server  
  - name: Restart the named
    command: "docker exec -it {{container_name}} rndc reload"
    become: yes 

  - name: parent subnet
    set_fact:
       parent_zone_name: "{{zone_name.split('.')[1]}}.{{zone_name.split('.')[2]}}"

  - name: subnet dns
    set_fact:
       subnet_zone_name: "{{zone_name.split('.')[0]}}"

  - name: add entry in parent dns
    lineinfile:
        path: /srv/docker/{{parent_dns_name}}/var/forward{{parent_zone_name}}
        line: "{{subnet_zone_name}}	IN	A	{{container_ip}} "

  - name: Restart the named of parent dns
    command: "docker exec -it {{parent_dns_name}} rndc reload"
    become: yes
