---
- hosts: localhost
  gather_facts: no
  vars:
    docker_filepath: ./docker_images/
    packages:
       - docker
  vars_files:
    - instance_vars.yml

  tasks:
    - debug:
         msg: "{{servers}}"

  # Install required packages
    - name: Install required packages for docker
      apt:
        name: "{{packages}}"
      become: yes

   # Create docker image if not exists
    - name: Create docker image if not exists
      docker_image:
        path: "{{docker_filepath}}/{{servers[item].os_type}}"
        name: "my{{servers[item].os_type}}"
        state: present
      with_items: "{{ servers | list }}"

    - name: Get the ip address of VPC DNS server
      shell: "docker exec -i {{ servers[item].vpc_dns }} /sbin/ifconfig {{servers[item].vpc_dns}}vif1 | grep 'inet' | cut -d: -f2 | awk '{print $2}'"
      become: yes
      with_items: "{{ servers | list }}"
      register: container_subnetip

    - name: debug
      set_fact:
         container_ip: "{{container_subnetip.results[0].stdout}}"

    - name: Extract gateway ip
      set_fact:
           gateway_ip: "{{container_ip.split('.')[0]}}.{{container_ip.split('.')[1]}}.{{container_ip.split('.')[2]}}.1"

    - name: Debug gateway ip
      debug:
         msg: "{{gateway_ip}}" 
