#!/bin/bash

set -x

init_config() {
  mv /named.conf.default /etc/named.conf
  mkdir /var/named/log
  chmod -R 0777 /var/named/log
  chown -R named:named /var/named/log
}

# Main Shell Script
init_config

if [[ ${1:0:1} = '-' ]]; then
  EXTRA_ARGS="$@"
  set --
elif [[ ${1} == '/usr/sbin/named' ]]; then
  EXTRA_ARGS="${@:2}"
  set --
fi

if [[ -z ${1} ]]; then
  echo "Starting DNS service..."
  sed 's/#PermitRootLogin/PermitRootLogin/' < /etc/ssh/sshd_config > /etc/ssh/sshd_config
  exec /usr/sbin/named -4 -u named -c /etc/named.conf -g ${EXTRA_ARGS}
  
else
  exec "$@"
fi
