#!/bin/bash

set -x


if [[ ${1:0:1} = '-' ]]; then
  EXTRA_ARGS="$@"
  set --
elif [[ ${1} == '/usr/sbin/named' ]]; then
  EXTRA_ARGS="${@:2}"
  set --
fi

if [[ -z ${1} ]]; then
  echo "Starting named..."
  exec /usr/sbin/named -4 -u named -c /etc/named.conf -g ${EXTRA_ARGS}
else
  exec "$@"
fi
