---
- hosts: localhost
  gather_facts: no
  vars:
    vm_disk_location: /var/lib/libvirt/images
    dns_image_location: /home/ece792/images/dns.img
    root_pass: root
  vars_files:
    - dns_vm_vars.yml

  tasks:
    - debug:
         msg: "{{dns_vms}}"
  
    # Install required packages
#    - name: Install required packages for libvirt, lxml
#      apt: 
#        name: "{{packages}}"
#      become: yes

    # Create an Linux type bridge
    - name: Create Linux Bridge
      command: "brctl addbr {{dns_vms[item].bridge_name}}"
      with_items: "{{ dns_vms | list }}"
      ignore_errors: true
      become: yes
    
    # Define a new network
    - name: Define Virtual Network
      virt_net:
        command: define
        name: "{{dns_vms[item].network_name}}"
        xml: "{{ lookup('template', 'templates/dns_bridge_template.xml.j2' ) }}"
      with_items: "{{ dns_vms | list }}"
      ignore_errors: true

    # Create and start a network
    - name: Create Virtual Network if not created
      virt_net:
        command: create
        name: "{{ dns_vms[item].network_name }}"
      with_items: "{{ dns_vms | list }}"
      ignore_errors: true
      become: yes
  
    # Set interface bridge up
    - name: Set Interface of bridges up
      command: "sudo ifconfig {{dns_vms[item].bridge_name}} up"
      with_items: "{{ dns_vms | list }}"
      ignore_errors: true
      become: yes

    # Create veth pair
    - name: Set Interface of bridges up
      command: "ip link add {{dns_vms[item].bridge_name}}vif1 type veth peer name {{dns_vms[item].bridge_name}}vif2"
      with_items: "{{ dns_vms | list }}"
      ignore_errors: true
      become: yes

    # Add vethpair interface to namespace
    - name: Add vethpair interface to namespace
      command: "ip link set {{dns_vms[item].bridge_name}}vif1 netns {{dns_vms[item].vpc_name}}_ns"
      with_items: "{{ dns_vms | list }}"
      ignore_errors: true
      become: yes

    # Attach another veth pair interface with bridge
    - name: Attach another vethpair interface to bridge
      command: "brctl addif {{dns_vms[item].bridge_name}} {{dns_vms[item].bridge_name}}vif2"
      with_items: "{{ dns_vms | list }}"
      ignore_errors: true
      become: yes

    # Assign ip to vethpair interface inside namespace
    - name: Assign ip to vethpair interface inside namespace
      command: "ip netns exec {{dns_vms[item].vpc_name}}_ns ifconfig {{dns_vms[item].bridge_name}}vif1 {{dns_vms[item].gateway_address}} up"
      with_items: "{{ dns_vms | list }}"
      ignore_errors: true
      become: yes

    # Add ip table rules NAT inside the vpc namespace for subnet
    - name: Add ip table rules NAT inside the vpc namespace for subnet
      command: "ip netns exec {{dns_vms[item].vpc_name}}_ns iptables -t nat -I POSTROUTING 1 -s {{dns_vms[item].subnet_ip}} ! -d {{dns_vms[item].subnet_ip}} -j MASQUERADE"
      with_items: "{{ dns_vms | list }}"
      ignore_errors: true
      become: yes

   # Provide  DHCP and DNS 
    - name: Make the interface of subnet to run dhcp server
      command: "ip netns exec {{dns_vms[item].vpc_name}}_ns dnsmasq --interface={{dns_vms[item].bridge_name}}vif1 --except-interface=lo --bind-interfaces --dhcp-range={{dns_vms[item].dhcp_range}}"
      with_items: "{{ dns_vms | list }}"
      ignore_errors: true
      become: yes
    
    # Get List of VM Disks
    - name: Get list of VM disks
      command: "ls {{ vm_disk_location }}"
      register: disks
      changed_when: "disks.rc != 0"
      become: yes
  
    #Copy VM Disk Image for DNS
    - name: Copy VM Disk Image for DNS
      copy:
        src: "{{dns_image_location}}"
        dest: "{{vm_disk_location}}/{{dns_vms[item].dns_vm_name}}.img"
      when: dns_vms[item].dns_vm_name not in disks.stdout
      with_items: "{{ dns_vms | list }}"
      become: yes

    # List of VMs
    - name: Get list of VMs
      virt:
        command: "list_vms"
      register: vms

    - debug:
         msg: "{{vms}}"
    - debug:
         msg: "{{dns_vms[item].dns_vm_name}}"
      with_items: "{{ dns_vms | list }}"

    #Define new vm
    - name: Define new vm
      virt:
        name: "{{dns_vms[item].dns_vm_name}}"
        command: define
        xml: "{{ lookup('template', 'templates/dns_vm_template.xml.j2') }}"
      with_items: "{{ dns_vms | list }}"
      become: yes


    # Create and start new vm
    - name: Start vm
      virt:
        name: "{{dns_vms[item].dns_vm_name}}"
        command: create
      with_items: "{{ dns_vms | list }}"
      become: yes

    # # Write to database or run this script seperately from shell
    # - name: Writing this newly created DNS VM to DB
    #   include: write_dns_vm_db.yml
    
